name: bringYourChianCodeAsNFT
on:
  pull_request:

env:
  TEST_NETWORK_CHAINCODE_IMAGE: localhost:5000/nftsample:latest
  TEST_NETWORK_CHAINCODE_NAME: nftsample
  TEST_NETWORK_CHAINCODE_LABEL: nft_1.0
jobs:
  bringYourChianCodeAsNFT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: true
      - uses: actions/setup-go@main
        with:
          go-version: 1.18
      - name: install kind
        run: go install sigs.k8s.io/kind@v0.12.0
      - name: check version
        run: kind version
      - name: install kubectl
        run: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - name: check version
        run: kubectl version || true
      - name: infra up
        run: ./infra.sh up
      - name: infra prometheus
        run: ./infra.sh prometheus
      - name: infra jaeger
        run: ./infra.sh jaeger
      - name: sleep as infra ready
        run: sleep 60
      - name: infra verify 
        run: ./infra.sh verify
      - name: Fabric network up
        run: cd ./SUT/fabric && ./network.sh up
      - name: sleep as pod ready
        run: sleep 60  
      - name: set up fabric channel
        run: cd ./SUT/fabric && ./network.sh channel
      - name: build NFT image
        run: cd ./SUT/fabric && ./network.sh buildchaincode ./chaincode/nftsamplecode
      - name: set up chaincode pod
        run: cd ./SUT/fabric && ./network.sh chaincode deploy
      - name: run Tape based traffic
        run:  cd ./Traffic/fabric && ./tape.sh NFT
      - name: sleep a while
        run: sleep 60
      - name: verify pods
        run: kubectl get po
      - name: save pod status
        run: kubectl get po | grep tape > log.out
      - name: verify tape
        run: kubectl describe po $(cat log.out|awk -F ' ' '{print $1}')
      - name: verify tape
        run: kubectl logs $(cat log.out|awk -F ' ' '{print $1}') -c tape
      - name: cleanup
        run: ./infra.sh down
